import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import QueryClientProviders from "@/provider/QueryClientProviders";
import MainLayout from "./components/MainLayout/MainLayout";
import AntProviders from "@/provider/AntProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body>
        <AntProviders>
          <QueryClientProviders>
            <MainLayout>{children}</MainLayout>
          </QueryClientProviders>
        </AntProviders>
      </body>
    </html>
  );
}
